
export const EnglishData = {
    about: "About",
    action: "Action",
    anotherAction: 'Form',
    something: "Something else here",
    resources: "Resources",
    welcomeMsg: " WELCOME TO PATH CHURCH",
    welcomePara: "Join our community of faith to find meaning, purpose and compassion.",
    pathDate: "PATH SUNDAYS • 9 A.M. & 10:30 A.M. IN PERSON • 11 A.M. ONLINE",
    join: "JOIN US",
    joinPara: "Welcome to the family. Watch this introduction to learn how to become a church member.",
    joinbtn: "WATCH",
    location: "OUR LOCATIONS",
    locationPara: " Path Church has different locations in the tristate area. Find the one that's closest to you.",
    locationbtn: "VISIT US",
    giveBack: "GIVE BACK",
    giveBackpara: " Learn how you can give back to the church and our community of faith.",
    giveBackbtn: "LEARN MORE",
    groups: "GROUPS + COACHES + MORE",
    groupsHead: " CONNECT WITH PEOPLE LIKE YOU",
    groupsPara: "You're not meant to go through life alone. We're here to help you find your people and help you grow as a person growth, whether through a life coach or the power of prayer.",
    care: "RECIEVE CARE",
    ourGroups: "OUR GROUPS",
    serveCity: "SERVE OUR CITY",
    yourFamily: "FOR YOUR FAMILY",
    yourFamilyHead: "FROM STUDENTS TO MINISTRIES",
    yourFamilyPara: "Let your children discover the power of becoming Path church's youth ministries.",
    kids: " FAITH KIDS",
    youth: "YOUTH",


    //about page constants

    aboutpage: "ABOUT",
    aboutpagetext: "Path Church is a diverse community of ordinary individuals who bravely place their trust in Jesus, allowing Him to perform extraordinary feats.",
    pathstory: "THE PATH STORY",
    stand: "WE STAND FOR LIVES CHANGED BY CHRIST",
    standtext: "Our Church started with a small group of people who used to congregate in a small living room in Millsboro, DE. Today they're over 500.",
    standtext1: `They posed inquiries such as, "Imagine a church that prioritizes others." This mindset centered on serving others has not only influenced our identity but also continues to shape us. As we embarked on establishing new branches and reaching various communities across Delaware, our mission has remained unwavering.`,
    standtext2: "Today, Path stands as a single church with multiple sites spread throughout Delaware. Each location offers a consistent, cohesive experience with music and a shared message delivered by a communicator that is broadcasted to every site.",
    standbtn: "MEET OUR TEAM",
    believe: "WHAT WE BELIEVE",
    believetext: "We believe that church isn't just about a building with a cross. It's about people's relationship with God and each other.",
    aboutgod: "ABOUT GOD",
    aboutgodtext: "Describe the item or answer the question so that site visitors who are interested get more information. You can emphasize this text with bullets, italics, or bold, and add links.",
    humanitytext: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, aliquam autem vitae laudantium natus eaque ab sit harum tempora officiis eligendi maiores culpa ratione illo nemo quisquam voluptas velit asperiores?",
    abouthumanity: "ABOUT HUMANITY",
    aboutsalvationtext: "Describe the item or answer the question so that site visitors who are interested get more information. You can emphasize this text with bullets, italics or bold, and add links.",
    aboutsalvation: "ABOUT SALVATION",
    aboutchurch: "ABOUT THE HOLY SPIRIT & THE CHURCH",
    aboutchurchtext: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati odio porro fugiat! Asperiores sequi nostrum labore itaque corrupti, cum voluptatum fugit iusto. Dolorem quo aliquid explicabo voluptatem omnis illo excepturi.",
    aboutbible: "ABOUT THE BIBLE",
    aboutbibletext: "Describe the item or answer the question so that site visitors who are interested get more information. You can emphasize this text with bullets, italics or bold, and add links.",
    freedom: "WE WERE MADE FOR FREEDOM",
    ourcorevalues: "OUR CORE VALUES",
    faith: "FAITH. COMMUNITY.",
    faithtext: "Path Church is a community of diverse people from all walks of life, who have decided to give Jesus the ultimate power and trust. This means we believe He will help us do what we can’t -forgive, transform, give back and nurture. We invite you to explore any of our recorded services (or stop by to see in person) to see Path's values and approach for yourself.",
    faithbtn: "VISIT US",
    livinglife: "LIVING LIFE INDIVIDUALLY, TOGETHER",
    livinglifetext: "Men and women everywhere are born to live together, not alone. As a closed-knit church, we believe we can all walk along our individual paths, together. With a strong shared sense of His love, each member of the Path community can find a way to live a wholesome life of faith while sharing the struggles, happy moments and wishes with other members of the church.",
    livingbtn: "JOIN A GROUP",
    lone: "LONE WOLVES DIE",
    vision: "VISION + MISSION",
    inspiring: "INSPIRING PEOPLE TO FOLLOW JESUS AND FEARLESSLY CHANGE THE WORLD",
    ourteam: "OUR TEAM",
    ourteamtext: "The men and women of Path's team are passionate about our church and providing members with everything they could possibly need.",
    mike: "JASON MITCHELL",
    mikeprof: "Senior Pastor",
    priyanka: "PRIYANKA CHOPRA",
    actor: "Cinema Actor",
    rgv: "RGV",
    rgvprof: "Cinema Director",
    bramii: "BHRAMII",
    memegod: "MEMES GOD",
    venky: "VENKATESH",
    hero: "CINEMA HERO",
    rajamouli: "RAJAMOULI",
    rakesh: "Rakesh Master",
    dance: "Dance Master",
    allu: "ALLU ARJUN",
    panhero: "Pan India Hero",
    aggi: "AGGI PETTA MACHA",
    aggiprof: "Fire Star",
    staydate: "STAY UP TO DATE",
    stayhead: "GET PATH'S LATEST",
    staytext: "Receive bi-weekly updates from the church, and get a heads up on upcoming events.",
    youremail: "Your Email",
    staybtn: "SUBMIT"
}
