export const FrenchData =
{
    about: "À propos",
    action: "Action",
    anotherAction: 'Une autre opération',
    something: "Quelque chose d'autre ici",
    resources: "Ressources",
    welcomeMsg: "BIENVENUE À L'ÉGLISE DU CHEMIN",
    welcomePara: "Rejoignez notre communauté de foi pour trouver un sens, un but et de la compassion.",
    pathDate: "DIMANCHES DU CHEMIN • 9H00 & 10h30 EN PERSONNE • 11 h EN LIGNE",
    join: "REJOIGNEZ-NOUS",
    joinPara: "Bienvenue à la famille. Regardez cette introduction pour savoir comment devenir membre d'église.",
    joinbtn: "MONTRE",
    location: "NOS EMPLACEMENTS",
    locationPara: "Path Church a différents emplacements dans la zone des trois états. Trouvez celui qui est le plus proche de vous.",
    locationbtn: "RENDEZ NOUS VISITE",
    giveBack: "REDONNER",
    giveBackpara: "Découvrez comment vous pouvez redonner à l'église et à notre communauté de foi.",
    giveBackbtn: "APPRENDRE ENCORE PLUS",
    groups: "GROUPES + AUTOCARS + PLUS",
    groupsHead: "CONNECTEZ - VOUS AVEC DES GENS COMME VOUS",
    groupsPara: "Vous n'êtes pas censé traverser la vie seul. Nous sommes là pour vous aider à trouver votre peuple et vous aider à grandir en tant que personne, que ce soit grâce à un coach de vie ou au pouvoir de la prière.",
    care: "RECEVOIR DES SOINS",
    ourGroups: "OUR GROUPS",
    serveCity: "SERVIR NOTRE VILLE",
    yourFamily: "POUR VOTRE FAMILLE",
    yourFamilyHead: "DES ÉTUDIANTS AUX MINISTÈRES",
    yourFamilyPara: "Laissez vos enfants découvrir le pouvoir de devenir les ministères de la jeunesse de l'église Path.",
    kids: "FOI ENFANTS",
    youth: "JEUNESSE",


    //about page constants
    aboutpage: "À PROPOS",
    aboutpagetext: "Path Church est une communauté diversifiée d'individus ordinaires qui placent courageusement leur confiance en Jésus, lui permettant d'accomplir des exploits extraordinaires.",
    pathstory: "L'HISTOIRE DU CHEMIN",
    stand: "NOUS REPRÉSENTONS DES VIES CHANGÉES PAR LE CHRIST",
    standtext: "Notre Église a commencé avec un petit groupe de personnes qui se rassemblaient dans un petit salon à Millsboro, DE. Aujourd'hui, ils sont plus de 500.",
    standtext1: `Ils ont posé des questions telles que "Imaginez une église qui donne la priorité aux autres." Cet état d'esprit centré sur le service aux autres a non seulement influencé notre identité mais continue également de nous façonner. Alors que nous nous lancions dans l'établissement de nouvelles succursales et que nous atteignions diverses communautés à travers le Delaware, notre mission est restée inébranlable.`,
    standtext2: "Aujourd'hui, Path se présente comme une seule église avec plusieurs sites répartis dans tout le Delaware. Chaque emplacement offre une expérience cohérente et cohérente avec de la musique et un message partagé délivré par un communicateur qui est diffusé sur chaque site.",
    standbtn: "RENCONTREZ NOTRE ÉQUIPE",
    believe: "CE QUE NOUS CROYONS",
    believetext: "Nous croyons que l'église n'est pas seulement un bâtiment avec une croix. Il s'agit de la relation des gens avec Dieu et entre eux.",
    aboutgod: "À PROPOS DE DIEU",
    aboutgodtext: "Décrivez l'article ou répondez à la question afin que les visiteurs du site intéressés obtiennent plus d'informations. Vous pouvez souligner ce texte avec des puces, des italiques ou des caractères gras et ajouter des liens.",
    humanitytext: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, aliquam autem vitae laudantium natus eaque ab sit harum tempora officiis eligendi maiores culpa ratione illo nemo quisquam voluptas velit asperiores?",
    abouthumanity: "À PROPOS DE L'HUMANITÉ",
    aboutsalvationtext: "Décrivez l'article ou répondez à la question afin que les visiteurs du site intéressés obtiennent plus d'informations. Vous pouvez souligner ce texte avec des puces, en italique ou en gras, et ajouter des liens.",
    aboutsalvation: "À PROPOS DU SALUT",
    aboutchurch: "À PROPOS DU SAINT-ESPRIT ET DE L'ÉGLISE",
    aboutchurchtext: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati odio porro fugiat! Asperiores sequi nostrum labore itaque corrupti, cum voluptatum fugit iusto. Dolorem quo aliquid explicabo voluptatem omnis illo excepturi.",
    aboutbible: "À PROPOS DE LA BIBLE",
    aboutbibletext: "Décrivez l'article ou répondez à la question afin que les visiteurs du site intéressés obtiennent plus d'informations. Vous pouvez souligner ce texte avec des puces, en italique ou en gras, et ajouter des liens.",
    freedom: "NOUS AVONS ÉTÉ FAITS POUR LA LIBERTÉ",
    ourcorevalues: "NOS VALEURS FONDAMENTALES",
    faith: "FOI. COMMUNAUTÉ.",
    faithtext: "Path Church est une communauté de personnes diverses de tous horizons, qui ont décidé de donner à Jésus le pouvoir et la confiance ultimes. Cela signifie que nous croyons qu'il nous aidera à faire ce que nous ne pouvons pas : pardonner, transformer, redonner et nourrir. Nous vous invitons à explorer l'un de nos services enregistrés (ou à vous arrêter pour voir en personne) pour voir les valeurs et l'approche de Path par vous-même.",
    faithbtn: "RENDEZ NOUS VISITE",
    livinglife: "VIVRE LA VIE INDIVIDUELLEMENT, ENSEMBLE",
    livinglifetext: "Partout, les hommes et les femmes sont nés pour vivre ensemble, pas seuls. En tant qu'église soudée, nous croyons que nous pouvons tous suivre nos chemins individuels, ensemble. Avec un fort sentiment partagé de son amour, chaque membre de la communauté Path peut trouver un moyen de vivre une vie de foi saine tout en partageant les luttes, les moments heureux et les souhaits avec d'autres membres de l'église.",
    livingbtn: "REJOINDRE UN GROUPE",
    lone: "LES LOUPS SOLITAIRES MEURENT",
    vision: "VISION + MISSION",
    inspiring: "INSPIRER LES GENS À SUIVRE JÉSUS ET CHANGER LE MONDE SANS PEUR",
    ourteam: "NOTRE ÉQUIPE",
    ourteamtext: "Les hommes et les femmes de l'équipe de Path sont passionnés par notre église et fournissent aux membres tout ce dont ils pourraient avoir besoin.",
    mike: "JASON MITCHELL",
    mikeprof: "Pasteur principal",
    priyanka: "PRIYANKA CHOPRA",
    actor: "Acteur de cinéma",
    rgv: "RGV",
    rgvprof: "Directeur de cinéma",
    bramii: "BHRAMII",
    memegod: "MEMES DIEU",
    venky: "VENKATESH",
    hero: "HÉROS DE CINÉMA",
    rajamouli: "RAJAMOULI",
    rakesh: "Rakesh Master",
    dance: "Maître de danse",
    allu: "ALLU ARJUN",
    panhero: "Héros de la Pan Inde",
    aggi: "AGGI PETTA MACHA",
    aggiprof: "Étoile de feu",
    staydate: "TIENS-TOI À JOUR",
    stayhead: "OBTENEZ LES DERNIÈRES NOUVELLES DE PATH",
    staytext: "Recevez des mises à jour bihebdomadaires de l'église et soyez informé des événements à venir.",
    youremail: "Votre e-mail",
    staybtn: "SOUMETTRE"
}
